# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: esnowbal <esnowbal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/06 10:47:13 by esnowbal          #+#    #+#              #
#    Updated: 2021/01/17 13:05:46 by esnowbal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= ex04

CLASSES= ex04.cpp

all: $(NAME)

$(NAME): $(CLASSES)
		clang++ -Wall -Wextra -Werror --std=c++98 $(CLASSES) -o $(NAME)

clean:
		rm -rf $(NAME)

fclean: clean

re: fclean all

run: $(NAME)
		./$(NAME)

mem: $(NAME)
		valgrind ./$(NAME)